# Travis CI configuration file. 
#
# Executes Unix shell commands instructions from "install", then "script" sections, then finally invokes "deploy" if successful. 
#
# Only required setup in Travis is to set the secure environment variable GITHUB_API_KEY to 
# a personal access token from this GitHub repo (to be found under Developer Settings)
#

matrix:
  include:
  
  - name: Python 3.6 Linux + doc + deploy
    os: linux
    python: 3.6
    env: XPYBUILD_DOC_AND_DEPLOY=true

  - name: Python 3.6 Windows
    os: windows
    # until Travis has language=python support on Windows, manually install using choco and sh(ell)
    language: sh
    before_install: 
      - unset GITHUB_API_KEY
      - choco install python --version 3.6
      - choco install jdk8 -params 'installdir=c:\\jdk1.8'
      - export "PATH=/c/Python36:/c/Python36/Scripts:/c/jdk1.8/bin:$PATH"

    # workaround for Travis Windows bug: disable secret filtering and hide secret env by unsetting it
    filter_secrets: false

  - name: Python 3.7 Linux
    os: linux
    python: 3.7
    env: XPYBUILD_PERFORMANCE_TESTS=true

  - name: Python 3.8 Linux
    os: linux
    python: 3.8

# Default Linux build runs on Ubuntu
language: python
cache: pip

install:
  - export XPYBUILD_VERSION=`cat XPYBUILD_VERSION`
  - export "TRAVIS_TAG=$XPYBUILD_VERSION"

  - if [[ -z $PY ]]; then export PY=python$TRAVIS_PYTHON_VERSION; fi
  - $PY -m pip install coverage codecov
  
  - $PY -m pip install pysys==1.5.0
  - env

# for running tests and building documentation:
script:
  # build documentation - fails if there are warnings
  - |
    if [[ -n $XPYBUILD_DOC_AND_DEPLOY ]]; then (
       set -e
       $PY -m pip install sphinx==2.2.0 sphinx-epytext=0.0.4
       # python2 ./xpybuild.py EPYDOC_ROOT=.
    )
    fi

  # run tests
  - cd tests/correctness
  - pysys.py --help
  - pysys.py run --threads auto -XpythonCoverage=true --exclude skip_ci --purge --record --mode ALL
  - cd ../performance
  - if [[ -n $XPYBUILD_PERFORMANCE_TESTS ]]; then pysys.py run --threads auto --exclude skip_ci --purge --record --mode ALL; fi
  - cd ../..

after_script:
  # upload Python code coverage
  - cd tests/coverage-python
  - codecov
  - cd ../..
  
deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: 
      - release-output/*.zip
    skip_cleanup: true
    overwrite: true
    on: 
       # TODO: re-add this branch: master
       condition: $XPYBUILD_DOC_AND_DEPLOY = true

    name: "xpybuild v$XPYBUILD_VERSION"
    body: This release adds <TODO>. There are also a number of bug fixes and other improvements. See CHANGELOG.md for a full list of changes. 
  
    # this is a draft release, allows manually editing details in github UI
    draft: true

  - provider: pages
    github-token: $GITHUB_API_KEY
    target-branch: gh-pages
    local-dir: release-output/doc/api/
    skip_cleanup: true
    keep-history: true
    project-name: "XPyBuild $XPYBUILD_VERSION"
    
    on: 
       branch: master
       condition: $XPYBUILD_DOC_AND_DEPLOY = true
       tags: true

