# Travis CI configuration file. 
#
# Executes Unix shell commands instructions from "install", then "script" sections, then finally invokes "deploy" if successful. 
#
# Only required setup in Travis is to set the secure environment variable GITHUB_API_KEY to 
# a personal access token from this GitHub repo (to be found under Developer Settings)
#

matrix:
  include:
  
  - name: Python 2.7 Linux + doc + deploy
    os: linux
    python: 2.7
    env: XPYBUILD_DOC_AND_DEPLOY=true
  
  - name: Python 2.7 Windows
    os: windows
    language: sh
    before_install: 
      - unset GITHUB_API_KEY
      - choco install python2 vcredist2008 -i vcpython27
      - choco install jdk8 -params 'installdir=c:\\jdk1.8'
      - export "PATH=/c/Python27:/c/Python27/Scripts:/c/jdk1.8/bin:$PATH"
    filter_secrets: false

# Default Linux build runs on Ubuntu
language: python
cache: pip

install:
  - export XPYBUILD_VERSION=`cat XPYBUILD_VERSION`
  - export "TRAVIS_TAG=$XPYBUILD_VERSION"

  - if [[ -z $PY ]]; then export PY=python$TRAVIS_PYTHON_VERSION; fi
  - $PY -m pip install coverage codecov
  
  - $PY -m pip install pysys==1.4.0

# for running tests and building documentation:
script:
  # build documentation - fails if there are warnings
  - |
    if [[ -n $XPYBUILD_DOC_AND_DEPLOY ]]; then (
       set -e
       $PY -m pip install epydoc
       $PY ./xpybuild.py EPYDOC_ROOT=.
    )
    fi

  # run tests
  - cd tests/correctness
  - pysys.py run --purge --threads auto -X PYTHON_COVERAGE=true --exclude skip_ci
  - cd ../..

after_script:
  # upload Python code coverage
  - cd tests
  - echo Uploading code coverage
  - codecov
  - cd ..
  
deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    file_glob: true
    file: 
      - release-output/*.zip
    skip_cleanup: true
    overwrite: true
    on: 
       branch: master
       condition: $XPYBUILD_DOC_AND_DEPLOY = true

    name: "xpybuild v$XPYBUILD_VERSION"
    body: This release adds <TODO>. There are also a number of bug fixes and other improvements. See CHANGELOG.md for a full list of changes. 
  
    # this is a draft release, allows manually editing details in github UI
    draft: true

  - provider: pages
    github-token: $GITHUB_API_KEY
    target-branch: gh-pages
    local-dir: release-output/doc/api/
    skip_cleanup: true
    keep-history: true
    project-name: "XPyBuild $XPYBUILD_VERSION"
    
    on: 
       branch: master
       condition: $XPYBUILD_DOC_AND_DEPLOY = true
       tags: true

